name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: yarn install

    - name: Install PostgreSQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Run Migrations
      run: |
        chmod +x migrations/run-migrations.sh
        ./migrations/run-migrations.sh up
      env:
        DB_CONNECTION_STRING: postgres://user:password@localhost:5432/test_db

    - name: Build Next.js App
      run: yarn build
      env:
        DB_CONNECTION_STRING: postgres://user:password@localhost:5432/test_db
        # Ensure consistent VAPID keys
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: BHo3FsXcoAdopBuFpA5Z2lpAbBuC986NMyha6JSvLkqzCOWF-qhJTyisuvBjP5s_O-848f5NsheoPa03q-BxRAE
        VAPID_PRIVATE_KEY: kSMLd0MDqnRAw2JVvEg79OSISg4XAdxTIiWzD18OGvw
        NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID: ${{ secrets.NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID }}

    # CACHE PLAYWRIGHT BROWSERS
    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
            ${{ runner.os }}-playwright-

    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium
      # Optimizations:
      # 1. Install ONLY chromium if we only use that in config
      # 2. --with-deps install sys deps

    - name: Run Playwright tests
      run: npx playwright test
      env:
        DB_CONNECTION_STRING: postgres://user:password@localhost:5432/test_db
        NEXT_PUBLIC_VAPID_PUBLIC_KEY: BHo3FsXcoAdopBuFpA5Z2lpAbBuC986NMyha6JSvLkqzCOWF-qhJTyisuvBjP5s_O-848f5NsheoPa03q-BxRAE
        VAPID_PRIVATE_KEY: kSMLd0MDqnRAw2JVvEg79OSISg4XAdxTIiWzD18OGvw
        NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID: ${{ secrets.NEXT_PUBLIC_DYNAMIC_ENVIRONMENT_ID }}
        DYNAMIC_TEST_ACCOUNT_OTP: ${{ secrets.DYNAMIC_TEST_ACCOUNT_OTP }}
        CI: true

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
